#-------------------------------------------------------
# Options to cicconf
#-------------------------------------------------------
options:
  template:
    ip: tech_sky130A/cicconf/ip_template.yaml
  project: jnw
  technology: sky130A

#-------------------------------------------------------
# Tools
#-------------------------------------------------------

#- Configuration. Cloining, update, status of this file
cicconf:
  remote: git@github.com:wulffern/cicconf.git
  revision: main

#- Simulation orchestration
cicsim:
  remote: git@github.com:wulffern/cicsim.git
  revision: main
  on_clone: python3 -m pip install --user -e .

#- Custom IC Creator - compiled analog blocks
ciccreator:
  remote: git@github.com:wulffern/ciccreator.git
  revision: master
  on_clone: cicconf clone --https

#- Transpiler and layout support
cicpy:
  remote: git@github.com:wulffern/cicpy.git
  revision: master
  on_clone: python3 -m pip install --user -e .

#-------------------------------------------------------
# TECHs
#-------------------------------------------------------
#- Carsten's PDK. Borders, symbols, loop stability
cpdk:
  remote: git@github.com:wulffern/cpdk.git
  revision: main

#- Technology used by sun/rply/cnr projects
tech_sky130B:
  remote: git@github.com:wulffern/tech_sky130B.git
  revision: main

#- Technology used by Tiny Tapeout
tech_sky130A:
  remote: git@github.com:wulffern/tech_sky130A.git
  revision: main

#-------------------------------------------------------
# SUN (2022)
# "It's not you, it's me, I don't like you." – Ayrun Sun, Farscape
#-------------------------------------------------------

#- PLL design (sch,lay)
sun_pll_sky130nm:
  remote: git@github.com:wulffern/sun_pll_sky130nm.git
  revision: main

#- Transistor library (sky130B,sch,lay)
sun_tr_sky130nm:
  remote: git@github.com:wulffern/sun_tr_sky130nm.git
  revision: main

#- Transistor library (sky130B,sch,lay)
sun_trb_sky130nm:
  remote: git@github.com:wulffern/sun_trb_sky130nm.git
  revision: main

#- 9-bit SAR (sky130A,sch,lay)
sun_sar9b_sky130nm:
  remote: git@github.com:wulffern/sun_sar9b_sky130nm.git
  revision: main

#-------------------------------------------------------
# RPLY (2023)
#"I say we take off and nuke the site from orbit.
# It's the only way to be sure.", Ellen Ripley, Aliens
#-------------------------------------------------------

#- PTAT bias source (sky130B, sch only)
rply_bias_sky130nm:
  remote: git@github.com:wulffern/rply_bias_sky130nm.git
  revision: main

#- Skywater 130nm tutorial (sky130B, sch/lay)
rply_ex0_sky130nm:
  remote: git@github.com:wulffern/rply_ex0_sky130nm.git
  revision: main

#-------------------------------------------------------
# CNR(2024)
#"In an insane world, it was the sanest choice."
# - Sarah Connor, Terminator 2: Judgment Day
#-------------------------------------------------------

#- Analog transitor library (sky130B, sch/lay)
cnr_atr_sky130nm:
  remote: git@github.com:wulffern/cnr_atr_sky130nm.git
  revision: main

#- Carsten's favorite differential OTA (sch only)
cnr_ota_sky130nm:
  remote: git@github.com:wulffern/cnr_ota_sky130nm.git
  revision: main

#- Carsten's Sigma-Delta temperature sensor (sch only)
cnr_gr00_sky130nm:
  remote: git@github.com:analogicus/cnr_gr00_sky130nm.git
  revision: main

#- Temperature sensor - Group 2 (Alireza, Bjørn, Sheikha, Youssef )
#- - PTAT bandgap core with PTAT current output and 1.2 VREF
#- - PTAT current into capacitor
#- - Comparator between VREF and capacitor voltage to check charge delay
#- SCH: CNR_GR02, LAY: CNR_GR02, DRC: OK, LVS: NOK
cnr_gr02_sky130nm:
  remote: git@github.com:analogicus/cnr_gr02_sky130nm.git
  revision: main

#- Temperature sensor - Group 3 (Daniel, Mangus, Martin, Vetle)
#- - PTAT bandgap core with PTAT current output and 1.2 VREF
#- - PTAT current into capacitor
#- - Comparator between VREF and capacitor voltage to check charge delay
#- SCH: TOPLEVEL, LAY: TOPLEVEL, DRC: OK, LVS: NOK (missing files)
#- Repository excluded cause of missing files
#cnr_gr03_sky130nm:
#  remote: git@github.com:analogicus/cnr_gr03_sky130nm.git
#  revision: main


#- Temperature sensor - Group 4 (Syver, Leidulf, Mohammad, Peter)
# - PTAT bandgap core with PTAT current output
# - PTAT current into capacitor
# - Comparator between VDD_1V8/2 and capacitor voltage to check charge delay
# SCH: CNR_GR04, LAY: CNR_GR04, DRC: NOK, LVS: NOK
#- Repository excluded because DRC is not ok
#cnr_gr04_sky130nm:
#  remote: git@github.com:analogicus/cnr_gr04_sky130nm.git
#  revision: main

#- Temperature sensor - Group 5 (Trond, Markus, Andrea)
#- - PTAT bandgap core with PTAT current output
#- - PTAT current into capacitor
#- - Comparator between VDD_1V8/2 and capacitor voltage to check charge delay
#- SCH: final, LAY: final, DRC: OK, LVS: NOK (missing files)
#- Repository excluded because it's so large
#cnr_gr05_sky130nm:
#  remote: git@github.com:analogicus/cnr_gr05_sky130nm.git
#  revision: main

#-------------------------------------------------------
# JNW(2025
# "You can use logic to justify almost anything. That's its power. And its flaw."
# - Kathryn Janeway, Star Trek Voyager: Prime Factors
#-------------------------------------------------------

#- Analog transistors
jnw_atr_sky130A:
  remote: git@github.com:analogicus/jnw_atr_sky130a.git
  revision: main

#- Standard library
jnw_tr_sky130A:
  remote: git@github.com:analogicus/jnw_tr_sky130a.git
  revision: main

#- Temperature sensor? (Carsten)
jnw_gr00_sky130A:
  remote: git@github.com:analogicus/jnw_gr00_sky130a.git
  revision: main
