

#-------------------------------------------------------
# Options to cicconf
#-------------------------------------------------------
options:
  template:
    ip: tech_sky130A/cicconf/lelo.yaml
  project: lelo
  technology: sky130A

#-------------------------------------------------------
# Tools
#-------------------------------------------------------
GDS2glTF:
  remote: git@github.com:wulffern/GDS2glTF.git
  revision: main
  description: GDS to 3D graphics
  on_clone: python3 -m pip install -r requirements.txt

cicconf:
  remote: git@github.com:wulffern/cicconf.git
  revision: main
  description: Configuration. Cloning, update, status of this file


cicsim:
  remote: git@github.com:wulffern/cicsim.git
  revision: main
  description: Simulation orchestration

cicspi:
  remote: git@github.com:wulffern/cicspi.git
  revision: main
  description: Python library to parse SPICE files




ciccreator:
  remote: git@github.com:wulffern/ciccreator.git
  revision: master
  description: Custom IC Creator - compiled analog blocks



cicpy:
  remote: git@github.com:wulffern/cicpy.git
  revision: master
  description: Transpiler and layout support


#-------------------------------------------------------
# TECHs
#-------------------------------------------------------

cpdk:
  remote: git@github.com:wulffern/cpdk.git
  revision: main
  description: Carsten's PDK. Borders, symbols, loop stability

tech_sky130B:
  remote: git@github.com:wulffern/tech_sky130B.git
  revision: main
  description: Technology used by sun/rply/cnr projects


tech_sky130A:
  remote: git@github.com:wulffern/tech_sky130A.git
  revision: main
  description: Technology used by Tiny Tapeout

#-------------------------------------------------------
# SUN (2022)
# "It's not you, it's me, I don't like you." – Ayrun Sun, Farscape
#-------------------------------------------------------


sun_pll_sky130nm:
  remote: git@github.com:wulffern/sun_pll_sky130nm.git
  revision: main
  description: A bad PLL design (sch,lay)


sun_tr_sky130nm:
  remote: git@github.com:wulffern/sun_tr_sky130nm.git
  revision: main
  description: Transistor Library and Logic Cells (sky130B,sch,lay)


sun_trb_sky130nm:
  remote: git@github.com:wulffern/sun_trb_sky130nm.git
  revision: main
  description: A analog transistor library (sky130B,sch,lay)

sun_sar9b_sky130nm:
  remote: git@github.com:wulffern/sun_sar9b_sky130nm.git
  revision: main
  description: A 9-bit SAR (on <https://tinytapeout.com/chips/tt06/>)

#-------------------------------------------------------
# RPLY (2023)
#"I say we take off and nuke the site from orbit.
# It's the only way to be sure.", Ellen Ripley, Aliens
#-------------------------------------------------------

#-
rply_bias_sky130nm:
  remote: git@github.com:wulffern/rply_bias_sky130nm.git
  revision: main
  description: A PTAT bias source (sky130B, sch only)


rply_ex0_sky130nm:
  remote: git@github.com:wulffern/rply_ex0_sky130nm.git
  revision: main
  description: Skywater 130nm tutorial (sky130B, sch/lay)

#-------------------------------------------------------
# CNR(2024)
#"In an insane world, it was the sanest choice."
# - Sarah Connor, Terminator 2: Judgment Day
#-------------------------------------------------------


cnr_atr_sky130nm:
  remote: git@github.com:wulffern/cnr_atr_sky130nm.git
  revision: main
  description: Analog transitor library (sky130B, sch/lay)


cnr_ota_sky130nm:
  remote: git@github.com:wulffern/cnr_ota_sky130nm.git
  revision: main
  description: Carsten's favorite differential OTA (sch only)


cnr_gr00_sky130nm:
  remote: git@github.com:analogicus/cnr_gr00_sky130nm.git
  revision: main
  description: Carsten's Sigma-Delta temperature sensor (sch only)

#- Temperature sensor - Group 2 (Alireza, Bjørn, Sheikha, Youssef )
#- - PTAT bandgap core with PTAT current output and 1.2 VREF
#- - PTAT current into capacitor
#- - Comparator between VREF and capacitor voltage to check charge delay
#- SCH: CNR_GR02, LAY: CNR_GR02, DRC: OK, LVS: NOK
cnr_gr02_sky130nm:
  remote: git@github.com:analogicus/cnr_gr02_sky130nm.git
  revision: main
  description: Temperature sensor - Group 2 (Alireza, Bjørn, Sheikha, Youssef )

#- Temperature sensor - Group 3 (Daniel, Mangus, Martin, Vetle)
#- - PTAT bandgap core with PTAT current output and 1.2 VREF
#- - PTAT current into capacitor
#- - Comparator between VREF and capacitor voltage to check charge delay
#- SCH: TOPLEVEL, LAY: TOPLEVEL, DRC: OK, LVS: NOK (missing files)
#- Repository excluded cause of missing files
#cnr_gr03_sky130nm:
#  remote: git@github.com:analogicus/cnr_gr03_sky130nm.git
#  revision: main


#- Temperature sensor - Group 4 (Syver, Leidulf, Mohammad, Peter)
# - PTAT bandgap core with PTAT current output
# - PTAT current into capacitor
# - Comparator between VDD_1V8/2 and capacitor voltage to check charge delay
# SCH: CNR_GR04, LAY: CNR_GR04, DRC: NOK, LVS: NOK
#- Repository excluded because DRC is not ok
#cnr_gr04_sky130nm:
#  remote: git@github.com:analogicus/cnr_gr04_sky130nm.git
#  revision: main

#- Temperature sensor - Group 5 (Trond, Markus, Andrea)
#- - PTAT bandgap core with PTAT current output
#- - PTAT current into capacitor
#- - Comparator between VDD_1V8/2 and capacitor voltage to check charge delay
#- SCH: final, LAY: final, DRC: OK, LVS: NOK (missing files)
#- Repository excluded because it's so large
#cnr_gr05_sky130nm:
#  remote: git@github.com:analogicus/cnr_gr05_sky130nm.git
#  revision: main

#-------------------------------------------------------
# JNW(2025)
# "You can use logic to justify almost anything. That's its power. And its flaw."
# - Kathryn Janeway, Star Trek Voyager: Prime Factors
#-------------------------------------------------------

#jnw:
#  remote: git@github.com:analogicus/jnw.git
#  revision: main

#-
jnw_atr_sky130a:
  remote: git@github.com:analogicus/jnw_atr_sky130A.git
  revision: main
  description: Analog transistor library (sky130A)

#- PTAT example
jnw_bias_sky130a:
  remote: git@github.com:wulffern/jnw_bias_sky130a.git
  revision: main
  description: PTAT bias source

#- Standard library
jnw_tr_sky130a:
  remote: git@github.com:analogicus/jnw_tr_sky130A.git
  revision: main
  description: transistor library and logic cells (sky130A)

#jnw_grex_sky130a:
#  remote: git@github.com:wulffern/jnw_grex_sky130a.git
#  revision: main

jnw_sv_sky130a:
  remote: git@github.com:wulffern/jnw_sv_sky130a.git
  revision: main
  description: Tutorial on SystemVerilog and ngspice simulation

#jnw_temp_sky130a:
#  remote: git@github.com:wulffern/jnw_temp_sky130a.git
#  revision: main

#- Temperature sensor? (Carsten)
#jnw_gr00_sky130a:
#  remote: git@github.com:analogicus/jnw_gr00_sky130A.git
#  revision: main

#jnw_gr01_sky130a:
#  remote: git@github.com:analogicus/jnw_gr01_sky130a.git
#  revision: main

#jnw_gr02_sky130a:
#  remote: git@github.com:analogicus/jnw_gr02_sky130a.git
#  revision: main

#jnw_gr03_sky130a:
#  remote: git@github.com:analogicus/jnw_gr03_sky130a.git
#  revision: main

#jnw_gr04_sky130a:
#  remote: git@github.com:analogicus/jnw_gr04_sky130a.git
#  revision: main

#jnw_gr05_sky130a:
#  remote: git@github.com:analogicus/jnw_gr05_sky130a.git
#  revision: main

#- https://analogicus.github.io/jnw_gr06_sky130a/
jnw_gr06_sky130a:
  remote: git@github.com:analogicus/jnw_gr06_sky130a.git
  revision: main
  description: Temperature Sensor by group 6 (On <https://tinytapeout.com/chips/ttsky25a/>)

#- https://analogicus.github.io/jnw_gr07_sky130a/
jnw_gr07_sky130a:
  remote: git@github.com:analogicus/jnw_gr07_sky130a.git
  revision: main
  description: Temperature Sensor by group 7 (On <https://tinytapeout.com/chips/ttsky25a/>)

#-------------------------------------------------------
# LELO(2026)
# "Chicken, goooood!"
# - Leeloo, Fifth element
#-------------------------------------------------------

#- Will still use skywater130, so the below are commented out

#tech_ihp13g2:
#  remote: git@github.com:wulffern/tech_ihp13g2.git
#  revision: main

lelo_temp_sky130a:
  remote: git@github.com:wulffern/lelo_temp_sky130a
  revision: main

#lelo_atr_ihp13g2:
#  remote: git@github.com:wulffern/lelo_atr_ihp13g2.git
#  revision: main

#lelo_sar9b_ihp13g2:
#  remote: git@github.com:wulffern/lelo_sar9b_ihp13g2.git
#  revision: main
