name: LELO


on:
  push:
    branches: [ main ]
    paths:
      - 'ci/**'
      - 'ip/**'
  pull_request:
    branches: [ main ]

jobs:
  lelo:
    runs-on: ubuntu-latest
    container:
      image: wulffern/aicex:24.04_0.1.6
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LELO_EX_SKY130A
        shell: bash
        run: |
          source ci/lelo_ex_sky130a/.bashrc
          cd ci/lelo_ex_sky130a
          make all
