# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main develop ]
  pull_request:
    branches: [ main develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6','3.7','3.8','3.9']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install setup
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt 
          pip3 install --no-deps   .
          cd tests/sim/BFX1_CV
          export PATH=/home/runner/.local/bin:$PATH
          make
          cd ../../ip
          export PROJECT=`pwd`/sun_test_gf130n
          cicsim ip SUN_TEST_GF130N module_template.yaml
